Feature
mikalai-udodau/spell-be pull request #1
Opened 2018-01-11 20:47 UTC by dimahetman

першая спроба ўнесці змены. Дабаўлено новыя словы, дабаўлены новыя суффіксы для існуючых слоў. Пашырэнне замен ў файле афіксаў. Замена слоў -іанізуе -іанізуюць на пачатковую форму
+іанізую з суфіксамі.
Дапісан README.

2018-01-11 20:50 UTC, dimahetman commented
дадатак

2018-01-13 16:14 UTC, mikalai-udodau requested changes

2018-01-13 16:14 UTC, mikalai-udodau commented on hunspell-dic/README
> +More informatioon about Hunspell dictionaty format see:
я не прыроджаны носьбіт англійскай, але думаю лепей будзе
For more information about Hunspell dictionary format see:

2018-01-13 16:14 UTC, mikalai-udodau commented on hunspell-dic/be_BY.affixes
> +REP и і       # памылкі альбо адсутнасць рэгістру
каментар трэба паправіць

2018-01-13 16:14 UTC, mikalai-udodau commented on hunspell-dic/be_BY.affixes
> +REP ъ '       # йод > ёд
тут таксама

2018-01-13 16:14 UTC, mikalai-udodau commented on hunspell-dic/dzeeprym.dic
> +выбітны/Z
гэты прыметнік трэба ў ext-prym.dic з іншым афіксам, г.зн. выбітны/V

2018-01-13 16:14 UTC, mikalai-udodau commented on hunspell-dic/dzejasl1.dic
> +выконвацца/dj
трэба перанесці ў ext-dzejasl1.dic

2018-01-13 16:14 UTC, mikalai-udodau commented on hunspell-dic/dzejasl1.dic
> +іанізую/chbj
лепш дадаць у ext-dzejasl1.dic як іанізавацца/dj
а тут запісаць як іанізую/cfh

2018-01-13 16:14 UTC, mikalai-udodau commented on hunspell-dic/ext-naz1.dic
> +дысперсія/E
трэба перанесці ў ext-naz2.dic

2018-01-13 16:14 UTC, mikalai-udodau commented on hunspell-dic/naz2.dic
> +хваля/EFP
СБМ і Граматычны назоўніка даюць форму "хваль", але не "хваляў", г.зн. афікс P тут не падыходзіць.

2018-01-16 17:21 UTC, dimahetman commented on hunspell-dic/README
> +More informatioon about Hunspell dictionaty format see:
так

2018-01-16 17:48 UTC, dimahetman commented on hunspell-dic/be_BY.affixes
> +REP и і       # памылкі альбо адсутнасць рэгістру
литара > літара (памылка выбару рэгістра клавіятуры)
так?

2018-01-16 18:46 UTC, dimahetman commented on hunspell-dic/dzeeprym.dic
> +выбітны/Z
згодны перанесці ў ext-prym.dic але /V не пдыходзіць
# цвёрдая аснова, націск на канцы
мне здаецца патрэбна /Z

2018-01-17 07:08 UTC, mikalai-udodau commented on hunspell-dic/be_BY.affixes
> +REP и і       # памылкі альбо адсутнасць рэгістру
я б напісаў "не тая раскладка", ці пакінуў толькі прыклад

2018-01-17 07:13 UTC, mikalai-udodau commented on hunspell-dic/dzeeprym.dic
> +выбітны/Z
Арфаграфічны НН і СБМ для гэтага слова даюць націск на і (г.зн. пасярэдзіне)

2018-01-18 17:18 UTC, dimahetman commented on hunspell-dic/dzeeprym.dic
> +выбітны/Z
дзякуй, а спасылка на крыніцу ёсць? усё не знайду як праверыць, а пачуцце казала іншае

2018-01-18 17:39 UTC, dimahetman commented on hunspell-dic/ext-naz1.dic
> +дысперсія/E
так, зраблю, але ў чым розніца?

2018-01-18 17:55 UTC, mikalai-udodau commented on hunspell-dic/dzeeprym.dic
> +выбітны/Z
http://slounik.org/search?dict=&search=%D0%B2%D1%8B%D0%B1%D1%96%D1%82%D0%BD%D1%8B&x=0&y=0

2018-01-18 17:56 UTC, mikalai-udodau commented on hunspell-dic/ext-naz1.dic
> +дысперсія/E
ext-naz1 для назоўнікаў першага скланення, ext-naz2 для другога

2018-01-18 17:57 UTC, mikalai-udodau commented on hunspell-dic/README
> +For more information about Hunspell dictionaty format see:
dictionaRy, кллск

2018-01-18 18:05 UTC, merged